export const BATTLE_DETAIL = 'BATTLE_DETAIL';
export const CURRENT_USER = 'CURRENT_USER';
export const BATTLE_LIST = 'BATTLE_LIST';
export const BATTLE_DETAIL_STARTED = 'BATTLE_DETAIL_STARTED';
export const BATTLE_DETAIL_SUCCESSED = 'BATTLE_DETAIL_SUCCESSED';
export const BATTLE_DETAIL_FAILED = 'BATTLE_DETAIL_FAILED';
