# Generated by Django 3.1.7 on 2021-06-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battling', '0007_team_pokemons'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='status',
            field=models.CharField(blank=True, choices=[('ONGOING', 'Ongoing'), ('SETTLED', 'Settled')], default='ONGOING', max_length=10),
        ),
    ]
