# Generated by Django 3.1.7 on 2021-06-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battling', '0008_battle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='status',
            field=models.CharField(blank=True, choices=[('OG', 'Ongoing'), ('ST', 'Settled')], default='OG', max_length=10),
        ),
    ]
