# Generated by Django 3.1.7 on 2021-08-10 18:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battling', '0009_auto_20210610_1639'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('battle', 'trainer')},
        ),
    ]
